### ISSUE TITLE
wechaty with padchat cannot login

### ISSUE THREAD

**Issue by tianshunjian** [botorange/puppet-padchat-patch#1]
I clone the "wechaty-getting-started", and change the initial code of Wechaty to use padchat. I install the “puppet-padchat-patch” via "npm install". Then i run "npm start". When I scan the qrcode first time, I got the Infos below in the console. However after I scan the new qrcode, there is nothing in the console while my phone shows that ipad wechat has logined. 

os：mac OS. the version of My wechaty-puppet-padchat is v0.17.15, and Wechaty is v0.22.1.

```
 INFO PadchatPatch start() with token: myToken, name: test, wxid: -106
[undefined] https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FYZKr7op0DA0LPG1VSXq3
Scan QR Code above to log in:
```

There is my code:
[starter-bot.js.zip](https://github.com/botorange/puppet-padchat-patch/files/2399450/starter-bot.js.zip)

The whole project:
[wechaty-getting-started](https://pan.baidu.com/s/1FyOOs0DkriKN7QEYXzircA) （baidu yunpan）
extract code (提取码): bymp

**Comment by ileadall42** [comment]
@tianshunjian  Can you login in successfully now?I seem to get the same with you .

**Comment by tianshunjian** [comment]
I have given up. After I scanned some times, my wechat account was forbidden to login. I do not want to try it again

**Comment by lijiarui** [comment]
@tianshunjian Sorry to hear that we will find another way to replace the patch function next month.

If you are intrested in this, you can try next month, thanks!
